export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
